MyJobs/MyJobs/Controllers/JobsController.cs
namespace MyJobs.Controllers
{
    using System.Security.Claims;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using MyJobs.Core.Models.Job;
    using MyJobs.Core.Repositories;
    using MyJobs.Core.Services.Contracts;
    using MyJobs.Infrastructure.Constants;

    public class JobsController : Controller
    {
        private readonly ICategoryService categoriesService;
        private readonly IDbRepository repository;
        private readonly IJobService jobService;

        public JobsController(
            ICategoryService categoriesService,
            IDbRepository repository,
            IJobService jobService)
        {
            this.categoriesService = categoriesService;
            this.repository = repository;
            this.jobService = jobService;
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Create()
        {
            var model = new CreateJobViewModel
            {
                CategoryItems = await this.categoriesService.GetAllCategories(),
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Create(CreateJobViewModel model)
        {
            bool doesCategoryExist = await this.categoriesService.CategoryExistById(model.CategoryId);

            if (!doesCategoryExist)
            {
                TempData[NotificationConstants.ErrorMessage] = NotificationConstants.NotExistingCategory;
                model.CategoryItems = await this.categoriesService.GetAllCategories();
                return View(model);
            }

            if (!ModelState.IsValid)
            {
                model.CategoryItems = await this.categoriesService.GetAllCategories();
                return View(model);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)!.Value;

            try
            {
                await this.jobService.CreateAsync(model, userId);
                TempData[NotificationConstants.InformationMessage] = "Your job offer is under review by the admin. We will notify you once a decision has been made.";
                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
                return View("CustomError");
            }

        }

        [HttpGet]
        public async Task<IActionResult> All(int page = 1)
        {
            const int ItemsPerPage = 5;
            var filterViewModel = await this.jobService.GetJobFilterViewModel();

            var model = new JobsListViewModel
            {
                PageNumber = page,
                ItemsPerPage = ItemsPerPage,
                Jobs = await this.jobService.GetAllJobs(page, ItemsPerPage),
                JobsTotalCount = await this.jobService.GetTotalJobCount(),
                JobFilter = filterViewModel,
            };
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var model = await this.jobService.GetSingleJob(id, userId!);
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Apply(int selectedResumeId, int jobId)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)!.Value;

            try
            {
                await this.jobService.Apply(selectedResumeId, userId, jobId);
                return Json(new { success = true, message = NotificationConstants.SuccessApply });
            }
            catch (ArgumentException ex)
            {
                if (ex.Message == NotificationConstants.AlreadyAppliedMessageError)
                {
                    return Json(new { success = false, message = ex.Message});
                }
                else if (ex.Message == NotificationConstants.NotExistingJob)
                {
                    return Json(new { success = false, message = ex.Message });
                }
                else if (ex.Message == NotificationConstants.AlreadyApprovedMessageError)
                {
                    return Json(new { success = false, message = ex.Message });
                }

                return View("CustomError");
            }
            catch (InvalidOperationException ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> ReceivedResumes(JobsWithCVsViewModel model)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            try
            {
                var jobViewModels = await this.jobService.GetJobsWithCV(model, userId!);

                return View(jobViewModels);
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Edit(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)!.Value;

            try
            {
                var model = await this.jobService.GetById(id, userId);
                model.CategoryItems = await this.categoriesService.GetAllCategories();

                return View(model);
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Edit(int id, EditJobViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await this.jobService.Update(id, model);
                return RedirectToAction(nameof(Details), new { id });
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await this.jobService.Delete(id);
            }
            catch (Exception)
            {
                return View("CustomError");
            }

            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public IActionResult Filter(string select, string[] selectedWorkingTimes, string locationSelect)
        {
            try
            {
                var filteredJobOffers = this.jobService.FilterJobOffers(select, selectedWorkingTimes, locationSelect);

                return PartialView("_FilteredJobOffersPartial", filteredJobOffers);
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }
    }
}

MyJobs/MyJobs/Controllers/ResumeController.cs
namespace MyJobs.Controllers
{
    using System.Security.Claims;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    using MyJobs.Core.Models.Resume;
    using MyJobs.Core.Repositories;
    using MyJobs.Core.Services.Contracts;
    using MyJobs.Infrastructure.Constants;
    using MyJobs.Infrastructure.Models;

    public class ResumeController : Controller
    {
        private readonly IResumeService resumeService;
        private readonly IDbRepository repository;

        public ResumeController(
            IResumeService resume,
            IDbRepository repository)
        {
            this.resumeService = resume;
            this.repository = repository;
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.Employee)]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Employee)]
        public async Task<IActionResult> Create(ResumeViewModel model, IFormFile? imageFile)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    using var memoryStream = new MemoryStream();
                    await imageFile.CopyToAsync(memoryStream);
                    byte[] imageBytes = memoryStream.ToArray();
                    model.Image = Convert.ToBase64String(imageBytes);
                }

                var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)!.Value;

                var employee = await this.repository.All<Employee>()
                                .FirstOrDefaultAsync(e => e.UserId == userId);

                if (employee == null)
                {
                    throw new ArgumentException("The requested employee was not found.");
                }

                await this.resumeService.SaveResume(model, employee.Id);

                byte[] resume = this.resumeService.GenerateResumePDF(model);

                return File(resume, "application/pdf", $"{employee.FirstName}_{employee.LastName}.pdf");
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }
    }
}

MyJobs/MyJobs/Views/Shared/CustomError.cshtml
<div class="d-flex align-items-center justify-content-center vh-100">
    <div class="text-center">
        <h1 class="display-1 fw-bold">404</h1>
        <p class="fs-3"> <span class="text-danger">Opps!</span> Something went wrong.</p>
        <p class="lead">
            An error occurred, please try again later.
        </p>
        <a asp-action="Index" asp-controller="Home" class="btn btn-primary">Return</a>
    </div>
</div>

MyJobs/MyJobs/Views/Shared/_FilterJobsPartial.cshtml
@using MyJobs.Core.Models.Job
@model JobsListViewModel

<div id="filterSection">
    <div class="job-category-listing mb-50">
        <div class="single-listing">
            <div class="small-section-tittle2">
                <h4>Job Category</h4>
            </div>
            <div class="select-job-items2">
                <select id="categorySelect" name="select">
                    <option value="">All Category</option>
                    @foreach (var category in Model.JobFilter.Categories)
                    {
                        <option value="@category.Key">@category.Value</option>
                    }
                </select>
            </div>
            <div class="select-Categories pt-80 pb-50">
                <div class="small-section-tittle2">
                    <h4>Job Type</h4>
                </div>
                @foreach (var workingTime in Model.JobFilter.WorkingTimes)
                {
                    <label class="container">
                        @workingTime
                        <input type="checkbox" name="selectedWorkingTimes" value="@workingTime">
                        <span class="checkmark"></span>
                    </label>
                }
            </div>
        </div>
        <div class="single-listing">
            <div class="small-section-tittle2">
                <h4>Job Location</h4>
            </div>
            <div class="select-job-items2">
                <select id="locationSelect" name="select">
                    <option value="">Anywhere</option>
                    @foreach (var townName in Model.JobFilter.TownNames)
                    {
                        <option value="@townName">@townName</option>
                    }
                </select>
            </div>
        </div>
        <br />
        <div class="text-center">
            <button  id="applyFiltersBtn" class="btn btn-primary">Apply Filters</button>
        </div>
    </div>
</div>

MyJobs/MyJobs/Views/Shared/_FilteredJobOffersPartial.cshtml
@using MyJobs.Infrastructure.Models
@model List<Job>

<div class="container">
    @if (Model.Count > 0)
    {
        <div id="jobListingSection" class="col-xl-9 col-lg-9 col-md-8">
            <section class="featured-job-area">
                <div class="container">
                    @foreach (var job in Model)
                    {
                        <div class="single-job-items mb-30">
                            <div class="job-items">
                                <div class="job-tittle job-tittle2">
                                    <h4>@job.Title</h4>
                                    <ul>
                                        <li>@(job.Category != null ? job.Category.Name : "")</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="items-link items-link2 f-right">
                                <a asp-action="GetById" asp-route-id="@job.Id">Details</a>
                            </div>
                        </div>
                    }
                </div>
            </section>
        </div>
    }
    else
    {
        <p>No job offers matching the selected filters.</p>
    }
</div>

MyJobs/MyJobs/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@using MyJobs.Core.Models.Notification
@using MyJobs.Infrastructure.Constants
@using MyJobs.Infrastructure.Data.Models.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyJobs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/logo.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <partial name="_NotificationPartial" />
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/MyJobs.png" alt="MyJobs Logo" class="logo">
            </a>
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity!.IsAuthenticated && User.IsInRole(RoleConstants.Employer))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Jobs" asp-action="Create">Create Job</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Jobs" asp-action="ReceivedResumes">Received Resumes</a>
                            </li>
                        }

                        @if (User.Identity!.IsAuthenticated && User.IsInRole(RoleConstants.Employee))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Resume" asp-action="Create">Create CV</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jobs" asp-action="All">All Jobs</a>
                        </li>
                    </ul>
                    @if (User.Identity.IsAuthenticated && User.IsInRole(RoleConstants.Employee))
                    {
                        string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="notificationsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-user-id="@userId">
                                <i class="fas fa-envelope fa-2x"></i>
                                <span class="badge rounded-pill badge-notification bg-danger" id="notificationsCount"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="notificationsDropdown">
                                <li>
                                    <div id="notificationsContainer"></div>
                                </li>
                            </ul>
                        </li>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="content-wrap">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; @DateTime.UtcNow.Year - MyJobs
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

MyJobs/MyJobs/Views/Shared/_MyApplicationsPartial.cshtml
@using MyJobs.Infrastructure.Models
@model List<Job>


@if (Model.Count > 0)
{


    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Job Title</th>
                <th>Category</th>
                <th>Company</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var job in Model)
            {
                <tr>
                    <td>@job.Title</td>
                    <td>@job.Category.Name</td>
                    <td>@job.Company.CompanyName</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h2 class="text-center">No jobs found!</h2>
}

MyJobs/MyJobs/Views/Shared/_MyJobsPartial.cshtml
@using MyJobs.Core.Models.Job
@{
    this.ViewData["Title"] = "My posted jobs.";
}
@model List<JobsViewModel>

<h1 class='text-center'>@ViewData["Title"]</h1>
<br />

@if (Model != null && Model.Any())
{
    @foreach (var job in Model)
    {
        <div class="single-job-items mb-30">
            <div class="job-items">
                <div class="job-tittle job-tittle2">
                    <h4>@job.Title</h4>
                    <ul>
                        <li>@job.CategoryName</li>
                    </ul>
                </div>
            </div>
            @if (!job.IsApproved)
            {
                <span>Аwaiting confirmation..</span>
            }
            <div class="items-link items-link2 f-right">
                <a asp-action="GetById" asp-controller="Jobs" asp-route-id="@job.Id">Details</a>
            </div>
        </div>
    }
}
else
{
    <h2 class="text-center">No jobs found!</h2>
}

MyJobs/MyJobs/Views/Shared/_NotificationPartial.cshtml
@if (TempData.ContainsKey(MyJobs.Infrastructure.Constants.NotificationConstants.ErrorMessage))
{
    <script>toastr.error('@TempData[NotificationConstants.ErrorMessage]');</script>
}

@if (TempData.ContainsKey(NotificationConstants.WarningMessage))
{
    <script>toastr.warning('@TempData[NotificationConstants.WarningMessage]');</script>
}

@if (TempData.ContainsKey(NotificationConstants.InformationMessage))
{
    <script>toastr.info('@TempData[NotificationConstants.InformationMessage]');</script>
}

@if (TempData.ContainsKey(NotificationConstants.SuccessMessage))
{
    <script>toastr.success('@TempData[NotificationConstants.SuccessMessage]');</script>
}

MyJobs/MyJobs/Views/Shared/_PersonalInformationPartial.cshtml
@using MyJobs.Core.Models.Profile
@{
    this.ViewData["Title"] = "Personal information";
}
@model UserProfileViewModel

<h1 class='text-center'>@ViewData["Title"]</h1>
<br />
@if (Model.IsEmployee)
{
    <div class="card text-center mx-auto">
        <div class="form-group">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control">
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" class="form-control">
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
}
else
{
    <div class="card text-center mx-auto">
        <div class="form-group">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control">
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" class="form-control">
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CompanyName"></label>
            <input asp-for="CompanyName" class="form-control">
            <span asp-validation-for="CompanyName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CompanyAddress"></label>
            <input asp-for="CompanyAddress" class="form-control">
            <span asp-validation-for="CompanyAddress" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CompanyPhoneNumber"></label>
            <input asp-for="CompanyPhoneNumber" class="form-control">
            <span asp-validation-for="CompanyPhoneNumber" class="text-danger"></span>
        </div>
    </div>
}
<div class="text-center">
    <a asp-action="EditProfile" asp-controller="Profile" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
</div>

MyJobs/MyJobs/Views/Shared/_RegisterEmployeePartial.cshtml
@using MyJobs.Core.Models.Account
@model RegisterViewModel
@{
    ViewData["Title"] = "Register as Employee";
}

<h1 class="text-center">@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-4 offset-md-4">
        <form id="registerForm" method="post">
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="text-center mb-3">
                <label asp-for="@Model.FirstName">First Name</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.FirstName" />
                <span asp-validation-for="@Model.FirstName" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.LastName">Last Name</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.LastName" />
                <span asp-validation-for="@Model.LastName" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Username">Username</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.Username" />
                <span asp-validation-for="@Model.Username" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Email">Email</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.Email" />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Password">Password</label>
                <input class="form-control" type="password" autocomplete="new-password" aria-required="true" asp-for="@Model.Password" />
                <span asp-validation-for="@Model.Password" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.PasswordRepeat">Confirm Password</label>
                <input class="form-control" type="password" autocomplete="new-password" aria-required="true" asp-for="@Model.PasswordRepeat" />
                <span asp-validation-for="@Model.PasswordRepeat" class="text-danger"></span>
            </div>
            <div class="text-center">
                <button id="registerSubmit" type="submit" class="btn btn-primary">Register</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MyJobs/MyJobs/Views/Shared/_RegisterEmployerPartial.cshtml
@using MyJobs.Core.Models.Account
@model RegisterViewModel
@{
    ViewData["Title"] = "Register as Employer";
}

<h1 class="text-center">@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-4 offset-md-4">
        <form id="registerForm" method="post">
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="text-center mb-3">
                <label asp-for="@Model.FirstName">First Name</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.FirstName" />
                <span asp-validation-for="@Model.FirstName" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.LastName">Last Name</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.LastName" />
                <span asp-validation-for="@Model.LastName" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Username">Username</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.Username" />
                <span asp-validation-for="@Model.Username" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Email">Email</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.Email" />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Password">Password</label>
                <input class="form-control" type="password" autocomplete="new-password" aria-required="true" asp-for="@Model.Password" />
                <span asp-validation-for="@Model.Password" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.PasswordRepeat">Confirm Password</label>
                <input class="form-control" type="password" autocomplete="new-password" aria-required="true" asp-for="@Model.PasswordRepeat" />
                <span asp-validation-for="@Model.PasswordRepeat" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.CompanyName">Company Name</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.CompanyName" />
                <span asp-validation-for="@Model.CompanyName" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.PhoneNumber">Company Phone Number</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.PhoneNumber" />
                <span asp-validation-for="@Model.PhoneNumber" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <label asp-for="@Model.Address">Company Address</label>
                <input class="form-control " autocomplete="username" aria-required="true" asp-for="@Model.Address" />
                <span asp-validation-for="@Model.Address" class="text-danger"></span>
            </div>
            <div class="text-center">
                <button id="registerSubmit" type="submit" class="btn btn-primary">Register</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}