MyJobs/MyJobs/Areas/Admin/Controllers/JobController.cs
namespace MyJobs.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    using MyJobs.Core.Services.Contracts;
    public class JobController : BaseController
    {
        private readonly IJobService jobService;

        public JobController(IJobService jobService)
        {
            this.jobService = jobService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var model = await this.jobService.GetAllJobs();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Approve(int id)
        {
            try
            {
                await this.jobService.ApproveJob(id);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await this.jobService.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }
    }
}

MyJobs/MyJobs/Controllers/EmployeeEmploymentController.cs
namespace MyJobs.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using MyJobs.Core.Services.Contracts;
    using MyJobs.Infrastructure.Constants;

    public class EmployeeEmploymentController : BaseController
    {
        private readonly IEmploymentService employmentService;

        public EmployeeEmploymentController(
            IEmploymentService employmentService)
        {
            this.employmentService = employmentService;
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Approve(int employeeId, int employerId, int companyId, int jobId)
        {
            try
            {
                await this.employmentService.Approve(employeeId, employerId, companyId, jobId);

                return RedirectToAction("ReceivedResumes", "Jobs");
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Reject(int employeeId, int employerId, int jobId)
        {
            try
            {
                await this.employmentService.Reject(employeeId, employerId, jobId);

                return RedirectToAction("ReceivedResumes", "Jobs");
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }
    }
}

MyJobs/MyJobs/Controllers/JobsController.cs
namespace MyJobs.Controllers
{
    using System.Security.Claims;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using MyJobs.Core.Models.Job;
    using MyJobs.Core.Repositories;
    using MyJobs.Core.Services.Contracts;
    using MyJobs.Infrastructure.Constants;

    public class JobsController : Controller
    {
        private readonly ICategoryService categoriesService;
        private readonly IDbRepository repository;
        private readonly IJobService jobService;

        public JobsController(
            ICategoryService categoriesService,
            IDbRepository repository,
            IJobService jobService)
        {
            this.categoriesService = categoriesService;
            this.repository = repository;
            this.jobService = jobService;
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Create()
        {
            var model = new CreateJobViewModel
            {
                CategoryItems = await this.categoriesService.GetAllCategories(),
            };

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Create(CreateJobViewModel model)
        {
            bool doesCategoryExist = await this.categoriesService.CategoryExistById(model.CategoryId);

            if (!doesCategoryExist)
            {
                TempData[NotificationConstants.ErrorMessage] = NotificationConstants.NotExistingCategory;
                model.CategoryItems = await this.categoriesService.GetAllCategories();
                return View(model);
            }

            if (!ModelState.IsValid)
            {
                model.CategoryItems = await this.categoriesService.GetAllCategories();
                return View(model);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)!.Value;

            try
            {
                await this.jobService.CreateAsync(model, userId);
                TempData[NotificationConstants.InformationMessage] = "Your job offer is under review by the admin. We will notify you once a decision has been made.";
                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
                return View("CustomError");
            }

        }

        [HttpGet]
        public async Task<IActionResult> All(int page = 1)
        {
            const int ItemsPerPage = 5;
            var filterViewModel = await this.jobService.GetJobFilterViewModel();

            var model = new JobsListViewModel
            {
                PageNumber = page,
                ItemsPerPage = ItemsPerPage,
                Jobs = await this.jobService.GetAllJobs(page, ItemsPerPage),
                JobsTotalCount = await this.jobService.GetTotalJobCount(),
                JobFilter = filterViewModel,
            };
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var model = await this.jobService.GetSingleJob(id, userId!);
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Apply(int selectedResumeId, int jobId)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)!.Value;

            try
            {
                await this.jobService.Apply(selectedResumeId, userId, jobId);
                return Json(new { success = true, message = NotificationConstants.SuccessApply });
            }
            catch (ArgumentException ex)
            {
                if (ex.Message == NotificationConstants.AlreadyAppliedMessageError)
                {
                    return Json(new { success = false, message = ex.Message});
                }
                else if (ex.Message == NotificationConstants.NotExistingJob)
                {
                    return Json(new { success = false, message = ex.Message });
                }
                else if (ex.Message == NotificationConstants.AlreadyApprovedMessageError)
                {
                    return Json(new { success = false, message = ex.Message });
                }

                return View("CustomError");
            }
            catch (InvalidOperationException ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> ReceivedResumes(JobsWithCVsViewModel model)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            try
            {
                var jobViewModels = await this.jobService.GetJobsWithCV(model, userId!);

                return View(jobViewModels);
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Edit(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)!.Value;

            try
            {
                var model = await this.jobService.GetById(id, userId);
                model.CategoryItems = await this.categoriesService.GetAllCategories();

                return View(model);
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Edit(int id, EditJobViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await this.jobService.Update(id, model);
                return RedirectToAction(nameof(Details), new { id });
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }

        [HttpPost]
        [Authorize(Roles = RoleConstants.Employer)]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await this.jobService.Delete(id);
            }
            catch (Exception)
            {
                return View("CustomError");
            }

            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public IActionResult Filter(string select, string[] selectedWorkingTimes, string locationSelect)
        {
            try
            {
                var filteredJobOffers = this.jobService.FilterJobOffers(select, selectedWorkingTimes, locationSelect);

                return PartialView("_FilteredJobOffersPartial", filteredJobOffers);
            }
            catch (Exception)
            {
                return View("CustomError");
            }
        }
    }
}

MyJobs/MyJobs/Views/Jobs/All.cshtml
@using MyJobs.Core.Models.Job
@model JobsListViewModel
@{
    this.ViewData["Title"] = $"All Jobs";
}

<h1 class='text-center'>@ViewData["Title"]</h1>
<br />

<div class="job-listing-area pt-120 pb-120">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-lg-3 col-md-4">
                <div class="row">
                    <div class="col-12">
                        <h4 class='text-center'>Filter Jobs</h4>
                    </div>
                </div>
                <partial name="_FilterJobsPartial" />
            </div>
            <div id="jobListingSection" class="col-xl-9 col-lg-9 col-md-8">
                <section class="featured-job-area">
                    <div class="container">
                        @Html.AntiForgeryToken()
                        @foreach (var job in Model.Jobs)
                        {
                            <div class="single-job-items mb-30">
                                <div class="job-items">
                                    <div class="job-tittle job-tittle2">
                                        <h4>@job.Title</h4>
                                        <ul>
                                            <li>@job.CategoryName</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="items-link items-link2 f-right">
                                    <a asp-action="Details" asp-route-id="@job.Id">Details</a>
                                </div>
                            </div>
                        }
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>

<nav id="paginationNav">
    <ul class="pagination justify-content-center">
        <li class="page-item @if(!Model.HasPreviousPage) {
        <text>disabled</text>
}">
            <a class="page-link" asp-action="All" asp-route-page="@Model.PreviousPageNumber">Previous</a>
        </li>
        @for (int i = Model.PageNumber - 3; i < Model.PageNumber; i++)
        {
            if (i > 0)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item active">
            <span class="page-link">
                @Model.PageNumber
                <span class="sr-only"></span>
            </span>
        </li>
        @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 3; i++)
        {
            if (i <= Model.PagesCount)
            {
                <li class="page-item"><a class="page-link" asp-action="All" asp-route-page="@i">@i</a></li>
            }
        }
        <li class="page-item @if(!Model.HasNextPage) {
        <text>disabled</text>
}">
            <a class="page-link" asp-action="All" asp-route-page="@Model.NextPageNumber">Next</a>
        </li>
    </ul>
</nav>

@section Scripts{
    <script>
        $(document).ready(function() {
            // Store the initial content of the job listing section (unfiltered job offers)
            var originalJobListing = $("#jobListingSection").html();

            // Retrieve the anti-forgery token value from the hidden input field
            var token = $('input[name="__RequestVerificationToken"]').val();

            $("#applyFiltersBtn").click(function() {
                // Retrieve the selected filter values (category, working times, location)
                var selectedCategory = $("#categorySelect").val();
                var selectedWorkingTimes = [];
                $("input[name='selectedWorkingTimes']:checked").each(function() {
                    selectedWorkingTimes.push($(this).val());
                });
                var selectedLocation = $("#locationSelect").val();

                // Check if all filters are empty (no filters applied)
                if (!selectedCategory && selectedWorkingTimes.length === 0 && !selectedLocation) {
                    // Restore the original job listing and display the pagination
                    $("#jobListingSection").html(originalJobListing);
                    document.getElementById("paginationNav").style.display = 'block';
                    return;
                }

                // Hide the pagination since filtering is applied
                document.getElementById("paginationNav").style.display = 'none';

                // AJAX Request
                $.ajax({
                    url: "/Jobs/Filter",
                    type: "POST",
                    headers: {
                        "RequestVerificationToken": token
                    },
                    // Data Sent to Server (filter values)
                    data: {
                        select: selectedCategory,
                        selectedWorkingTimes: selectedWorkingTimes,
                        locationSelect: selectedLocation
                    },
                    // AJAX Request Success Callback
                    success: function(data) {
                        // Update the job listing section with the filtered data
                        $("#jobListingSection").html(data);
                    },
                    error: function() {
                        console.log("Error occurred while filtering job offers.");
                    }
                });
            });
        });
    </script>
}

MyJobs/MyJobs/Views/Jobs/Create.cshtml
@using MyJobs.Core.Models.Job
@model CreateJobViewModel
@{
    this.ViewData["Title"] = "Add new job";
    var categoryItems = this.Model.CategoryItems.Select(x => new SelectListItem(x.Value, x.Key));
}

<h1 class='text-center'>@this.ViewData["Title"]</h1>
<form method="post" class="col-md-6 offset-md-3">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="TownName"></label>
        <input asp-for="TownName" class="form-control">
        <span asp-validation-for="TownName" class="text-danger"></span>
    </div>
     <div class="form-group">
        <label asp-for="WorkingTime"></label>
        <input asp-for="WorkingTime" class="form-control">
        <span asp-validation-for="WorkingTime" class="text-danger"></span>
    </div>
     <div class="form-group">
        <label asp-for="Salary"></label>
        <input asp-for="Salary" class="form-control">
        <span asp-validation-for="Salary" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control" rows="4"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Requirements"></label>
        <textarea asp-for="Requirements" class="form-control" rows="4"></textarea>
        <span asp-validation-for="Requirements" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Responsibilities"></label>
        <textarea asp-for="Responsibilities" class="form-control" rows="4"></textarea>
        <span asp-validation-for="Responsibilities" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Offering"></label>
        <textarea asp-for="Offering" class="form-control" rows="4"></textarea>
        <span asp-validation-for="Offering" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId"></label>
        <select asp-for="CategoryId" class="form-control" asp-items="categoryItems"></select>
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <hr />
    <div class="container">
        <div class="row">
            <div class='text-center'>
                <input type="submit" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MyJobs/MyJobs/Views/Jobs/Details.cshtml
@using MyJobs.Core.Models.Job
@model SingleJobViewModel
@{
    this.ViewData["Title"] = @Model.Title;
    DateTime createdOn = Model.CreatedOn;
    TimeSpan daysSincePosted = DateTime.Today - createdOn.Date;
    int daysPostedAgo = (int)daysSincePosted.TotalDays;
    string postedAgoText;
    if (daysPostedAgo == 0)
    {
        postedAgoText = "Today";
    }
    else if (daysPostedAgo == 1)
    {
        postedAgoText = "1 day ago";
    }
    else
    {
        postedAgoText = $"{daysPostedAgo} days ago";
    }
}
<div class="job-post-company pt-120 pb-120">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-xl-7 col-lg-8">
                <div class="single-job-items mb-50">
                    <div class="job-items">
                        <div>
                            <h2 class="justify-content center">@this.ViewData["Title"]</h2>
                            @if (Model.IsOwner)
                            {
                                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
                                <hr />
                                <form asp-action="Delete" id="deleteForm" asp-route-id="@Model.Id">
                                </form>
                                <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">Delete</button>
                            }
                            <hr />
                        </div>
                    </div>
                </div>

                <div class="job-post-details">
                    <div class="post-details1 mb-50">
                        <div class="small-section-tittle">
                            <h3>Job Description</h3>
                        </div>
                        <p>@Model.Description</p>
                    </div>
                    <div class="post-details2  mb-50">
                        <div class="small-section-tittle">
                            <h3>Required Knowledge, Skills, and Abilities</h3>
                        </div>
                        @foreach (var req in Model.Requirements.Split(';'))
                        {
                            if (!string.IsNullOrWhiteSpace(req))
                            {
                                <span>&#8226; @req.Trim()</span>
                                <br />
                            }
                        }
                    </div>
                    <div class="post-details2  mb-50">
                        <div class="small-section-tittle">
                            <h3>Responsibilities</h3>
                        </div>
                        @foreach (var req in Model.Responsibilities.Split(';'))
                        {
                            if (!string.IsNullOrWhiteSpace(req))
                            {
                                <span>&#8226; @req.Trim()</span>
                                <br />
                            }
                        }
                    </div>
                    <div class="post-details2  mb-50">
                        <div class="small-section-tittle">
                            <h3>Offering</h3>
                        </div>
                        @foreach (var req in Model.Offering.Split(';'))
                        {
                            if (!string.IsNullOrWhiteSpace(req))
                            {
                                <span>&#8226; @req.Trim()</span>
                                <br />
                            }
                        }
                    </div>
                </div>

            </div>
            <div class="col-xl-4 col-lg-4">
                <div class="post-details3  mb-50">
                    <div class="small-section-tittle">
                        <h4>Job Overview</h4>
                    </div>
                    <ul>
                        <li>Posted : <span>@postedAgoText</span></li>
                        <li>Location : <span>@Model.Town</span></li>
                        <li>Salary : <span>$@Model.Salary</span></li>
                        <li>Working Time : <span>@Model.WorkingTime</span></li>
                    </ul>
                    @if (!Model.IsOwner)
                    {
                        <div class="apply-btn2">
                            <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#resumeSelectionModal">Apply Now</a>
                            @*<a asp-action="Apply" asp-route-id="@Model.Id" class="btn btn-primary">Apply Now</a>*@
                        </div>
                    }
                </div>
                <div class="post-details4  mb-50">
                    <div class="small-section-tittle">
                        <h4>Company Information</h4>
                    </div>
                    <ul>
                        <li>Name: <span>@Model.CompanyName </span></li>
                        <li>Employer Name:<span>@Model.EmployerFirstName @Model.EmployerLastName</span></li>
                        <li>Company Phone number:<span>@Model.PhoneNumber</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="deleteConfirmationModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete job</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete @Model.Title?</p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-danger" onclick="deleteForm.submit()">Delete</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="resumeSelectionModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Select Resume</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Choose one of your resumes:</p>
                <!-- Add a form to submit the selected resume -->
                <form id="applyForm" asp-route-jobId="@Model.Id">
                    @Html.AntiForgeryToken()
                    <div id="resumesContainer">
                    </div>
                    <input type="hidden" id="jobId" name="jobId" value="@Model.Id" />
                    <input type="hidden" id="selectedResumeId" name="selectedResumeId" value="" />
                </form>
            </div>
            <div class="modal-footer">
                <!-- Call the JavaScript function to submit the form -->
                <button type="button" class="btn btn-primary" onclick="submitApplication()">Send</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        function loadUserResumes() {
            var token = $('input[name="__RequestVerificationToken"]').val();
            $.ajax({
                url: '/Profile/GetUserResumes',
                method: 'GET',
                dataType: 'json',
                success: function(data) {
                    const resumesContainer = $('#resumesContainer');
                    resumesContainer.empty();
                    let valuesArray = data.$values;

                    valuesArray.forEach(resume => {
                        const radioDiv = $('<div>').addClass('form-check');
                        const radioInput = $('<input>')
                            .addClass('form-check-input')
                            .attr('type', 'radio')
                            .attr('name', 'selectedResume')
                            .val(resume.Id);
                        const radioLabel = $('<label>')
                            .addClass('form-check-label')
                            .text(resume.Title);

                        radioDiv.append(radioInput);
                        radioDiv.append(radioLabel);

                        resumesContainer.append(radioDiv);
                    });

                },
                error: function(error) {
                    console.error('Error fetching user resumes:', error);
                }
            });
        }

        $('#resumeSelectionModal').on('show.bs.modal', function() {
            loadUserResumes();
        });


        function submitApplication() {
            //var token = $('input[name="__RequestVerificationToken"]').val();
            // Get the selected resume ID
            const selectedResumeId = $('input[name="selectedResume"]:checked').val();

            console.log(selectedResumeId);

            if (!selectedResumeId) {
                alert('Please select a resume.');
                return;
            }

            $('#selectedResumeId').val(selectedResumeId);
            const formData = selectedResumeId;

            const form = $('#applyForm');
            $.ajax({
                url: '/Jobs/Apply',
                method: 'POST',
                data: form.serialize(),
                dataType: 'json',
                success: function(response) {
                    if (!response.success) {
                        toastr.error(response.message)
                    } else {
                        toastr.success(response.message);
                    }
                },
                error: function(error) {
                    console.error('Error response:', error.responseText);
                    toastr.error(error);
                }
            });

            $('#resumeSelectionModal').modal('hide');
        }
    </script>
}

MyJobs/MyJobs/Views/Jobs/ReceivedResumes.cshtml
@using MyJobs.Core.Models.Job
@model List<JobsWithCVsViewModel>
@{
    this.ViewData["Title"] = "Received resumes";
}

@if (Model.Count() == 0)
{
    <h2 class="text-center">No received resumes yet!</h2>
}
<div class="card-container">
    @foreach (var jobViewModel in Model)
    {
        <h3>@jobViewModel.Job.Title</h3>
        @foreach (var cv in jobViewModel.CVs)
        {
            string name = $"{cv.Employee.FirstName}  {cv.Employee.LastName}";
            string formattedDate = cv.DateOfBirth.ToString("dd.MM.yyyy");
            <div class="card" style="width: 18rem;">
                <img src="data:image/jpeg;base64,@cv.Image" class="card-img-top" alt="CV Image">
                <div class="card-body">
                    <h5 class="card-title">@cv.Title</h5>
                    <p class="card-text">Name: @name</p>
                    <p class="card-text">Address: @cv.Address</p>
                    <p class="card-text">Summary: @cv.Summary</p>
                    <p class="card-text">Date of Birth: @formattedDate</p>
                    <p class="card-text">Gender: @cv.Gender</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Education: @cv.Education</li>
                    <li class="list-group-item">Experience: @cv.Experience</li>
                    <li class="list-group-item">Skills: @cv.Skills</li>
                    <li class="list-group-item">Phone Number: @cv.PhoneNumber</li>
                </ul>
                <div class="card-body">
                    <form method="post" asp-action="Approve" asp-controller="EmployeeEmployment">
                        <input type="hidden" name="employeeId" value="@cv.EmployeeId" />
                        <input type="hidden" name="employerId" value="@jobViewModel.Job.EmployerId" />
                        <input type="hidden" name="companyId" value="@jobViewModel.Job.CompanyId" />
                        <input type="hidden" name="jobId" value="@jobViewModel.Job.Id" />

                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-primary btn-block">Approve</button>
                            </div>
                        </div>
                    </form>
                    <br />
                    <form method="post" asp-action="Reject" asp-controller="EmployeeEmployment">
                        <input type="hidden" name="employeeId" value="@cv.EmployeeId" />
                        <input type="hidden" name="employerId" value="@jobViewModel.Job.EmployerId" />
                        <input type="hidden" name="companyId" value="@jobViewModel.Job.CompanyId" />
                        <input type="hidden" name="jobId" value="@jobViewModel.Job.Id" />

                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger btn-block">Reject</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        }
    }
</div>